function Arrays = arrayparset
%ARRAYPARSET configures 6 different antenna arrays.

% Copyright 2016 The MathWorks, Inc.

numAZ = 120; 
Az = linspace(-180, 180-1/numAZ, numAZ); % YS: This should simply be -180:3:177
pattern(1,:,1,:) = winner2.dipole(Az,12); 

Arrays(1) = winner2.AntennaArray( ...   % ULA-2 1cm spacing
    'ULA', 2, 0.01, ...    
    'FP-ECS', pattern, ...
    'Azimuth', Az);    
Arrays(2) = winner2.AntennaArray( ...   % ULA-4 1cm spacing
    'ULA', 4, 0.01, ...    
    'FP-ECS', pattern, ...
    'Azimuth', Az);         
Arrays(3) = winner2.AntennaArray( ...   % ULA-8 1cm spacing
    'ULA', 8, 0.01, ...    
    'FP-ECS', pattern, ...
    'Azimuth', Az);     
Arrays(4) = winner2.AntennaArray( ...   % UCA-4 1cm radius
    'UCA', 4, 0.01, ...    
    'FP-ECS', pattern, ...
    'Azimuth', Az);    
Arrays(5) = winner2.AntennaArray( ...   % UCA-8 1cm radius
    'UCA', 8, 0.01, ...    
    'FP-ECS', pattern, ...
    'Azimuth', Az);    
Arrays(6) = winner2.AntennaArray( ...   % Isotropic antenna
    'ULA', 2, 3e8/5.25e9*0.5, ... 
    'FP-ECS', ones(2, 2, 1, 360)); 

% [EOF]