function sweepParameters = generateSweepParameters(Simulation) 
	% Constructs the sweep parameters structure to store sweep state for each user
	%
	% :param Simulation: Monster instance
	% :returns sweepParameters: sweep parameters for each UE

	enbList(1:length(Simulation.Stations)) = struct('eNodeBId', 0, 'angle', 0, 'sinr', 0); 

	sweepParameters(1: length(Simulation.Users)) = struct(...
		'ueId', 0,...
		'eNodeBList', enbList,...
		'timeLastAssociation', 0,...
		'hysteresisTimer', 0,...
		'rotationIncrement', 90,...
		'currentAngle', 0,...
		'maxAngle', 360,...
		'minAngle', 2);
	for iUser = 1:length(Simulation.Users)
		% assign the id to an empty slot in the sweepParameters
		sweepParameters(iUser).ueId = Simulation.Users.NCellID;

		% TODO other initialisation?
	end

end